
services:
  
  pets:
    build:
      context: ./apps/veterinary_clinic/pets/
      dockerfile: Dockerfile
    ports:
      - 8081:8080

  owners:
    build:
      context: ./apps/veterinary_clinic/owners/
      dockerfile: Dockerfile
    ports:
      - 8082:8080

  doctors:
    build:
      context: ./apps/veterinary_clinic/doctors/
      dockerfile: Dockerfile
    ports:
      - 8083:8080

  krakend:
    build:
      context: ./apps/krakend
      dockerfile: Dockerfile
    ports:
      - 8080:8080