networks:
  net:

services:

  pets:
    build:
      context: ./apps/veterinary_clinic/pets/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 8081:8080

  owners:
    build:
      context: ./apps/veterinary_clinic/owners/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 8082:8080

  doctors:
    build:
      context: ./apps/veterinary_clinic/doctors/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 8083:8080

  krakend:
    image: devopsfaith/krakend:2.6.3
    volumes:
      - ./apps/krakend/krakend.json:/etc/krakend/krakend.json
    networks:
      - net
    ports:
      - 8080:8080
      - 8001:9090

  keycloak:
    image: keycloak/keycloak
    networks:
      - net
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]

  grafana:
    image: grafana/grafana
    networks:
      - net
    ports:
      - "3000:3000"

  alloy:
    image: grafana/alloy
    environment:
      - ALLOY_TEMPO_ENDPOINT=http://tempo:4317
      - ALLOY_MIMIR_ENDPOINT=http://mimir:9009/api/v1/push
      - ALLOY_LOKI_ENDPOINT=http://loki:3100/loki/api/v1/push
    networks:
      - net
    ports:
      - 12345:12345
    volumes:
      - ./apps/alloy/config/config.alloy:/etc/alloy/config.alloy

  tempo-init:
    image: &tempoImage grafana/tempo
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./apps/tempo/data:/var/tempo

  tempo:
    image: *tempoImage
    networks:
      - net
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./apps/tempo/config/tempo.yaml:/etc/tempo.yaml
      - ./apps/tempo/data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"    # tempo
      - "9095:9095"    # tempo grpc
      - "4317:4317"    # otlp grpc
      - "4318:4318"    # otlp http
      - "9411:9411"    # zipkin
    depends_on:
      - tempo-init

  mimir:
    image: grafana/mimir
    networks:
      - net
    command: ["-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"
    volumes:
      - ./apps/mimir/mimir.yaml:/etc/mimir.yaml

  loki-init:
    image: &lokiImage grafana/loki
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/loki"
    volumes:
      - ./apps/loki/data:/var/loki

  loki:
    image: *lokiImage
    networks:
      - net
    ports:
      - "3100:3100"
    command: [ "-config.file=/etc/loki.yaml" ]
    volumes:
      - ./apps/loki/config/loki.yaml:/etc/loki.yaml
      - ./apps/loki/data:/var/loki
    depends_on:
      - loki-init

  # prometheus:
  #   image: prom/prometheus
  #   networks:
  #     - net
  #   ports:
  #     - "9090:9090"
  #   command:
  #     - --web.enable-remote-write-receiver
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   volumes:
  #     - ./apps/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./apps/prometheus/data:/prometheus
